version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
      - ./frontend:/frontend
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-test-key-for-testing}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./chatbot.db}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-4o}
      - DEFAULT_TEMPERATURE=${DEFAULT_TEMPERATURE:-0.7}
      - CORS_ORIGINS=${CORS_ORIGINS:-["*"]}
      - DEBUG=${DEBUG:-false}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Optional test service
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
      - ./tests:/tests
    environment:
      - OPENAI_API_KEY=sk-test-key-for-testing
      - DATABASE_URL=sqlite:///./test_chatbot.db
      - DEFAULT_MODEL=gpt-4o
      - DEFAULT_TEMPERATURE=0.7
      - CORS_ORIGINS=["*"]
      - DEBUG=true
    command: ["python", "-m", "pytest", "/tests/", "-q", "--tb=short"]
    profiles:
      - test