name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: flywheel:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run tests in container
      run: |
        docker run --rm \
          -e OPENAI_API_KEY=sk-test-key-for-testing \
          -e DATABASE_URL=sqlite:///./test_chatbot.db \
          -e DEBUG=true \
          flywheel:test pytest -q --tb=short
          
    - name: Test Docker Compose
      run: |
        echo "OPENAI_API_KEY=sk-test-key-for-testing" > .env.test
        docker compose -f docker-compose.yml --env-file .env.test run --rm test
        
    - name: Verify application starts
      run: |
        docker run -d --name test-app -p 8000:8000 \
          -e OPENAI_API_KEY=sk-test-key-for-testing \
          flywheel:test
        sleep 10
        curl -f http://localhost:8000/health
        docker stop test-app
        docker rm test-app
